In [2]:
from bs4 import BeautifulSoup as bs
import requests
link = "https://www.usagold.com/reference/prices/goldhistory.php"

In [3]:
headers={'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0'}
source = requests.get(link, headers=headers).text
# print(source)

In [6]:
soup = bs(source,"html.parser")

In [7]:
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <title>\n   Daily Gold Price History\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>\n  <meta content="width=device-width, initial-scale=1" name="viewport"/>\n  <!-- Global site tag (gtag.js) - Google Analytics -->\n  <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-113422341-1">\n  </script>\n  <!-- BEGIN ASSET LIST -->\n  <link href="//www.usagold.com/css/goldpricehistory.css?version=6.17.2020" rel="stylesheet" type="text/css"/>\n  <!-- BEGIN ASSET LIST -->\n  <!-- INCLUDE Bootstrap Stylesheet -->\n  <link href="https://www.usagold.com/css/bootstrap.min.css" rel="stylesheet"/>\n  <!-- INCLUDE Main USAGOLD Stylesheet : This is the main stylesheet and contains most usagold specific styles -->\n  <link href="https://www.usagold.com/css/usagold-main.css?ver=20.11.3" rel="stylesheet"/>\n  <!-- INCLUDE Fontawesome Stylesheet : This is used for icons on the site -->\n  <link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" media="screen" rel="stylesheet"/>\n  <!-- JAVASCRIPT : Code to add purechat to the site -->\n  <!-- END ASSET LIST -->\n </head>\n <body>\n  <a class="screen-reader-only" href="#maincontent">\n   Skip to main content\n  </a>\n  <a class="screen-reader-only" href="https://www.usagold.com/cpmforum/help-accessibility/">\n   Read accessibility\n\tstatement\n  </a>\n  <div class="container">\n   <div class="nomobile" id="header">\n    <div class="row header-brand">\n     <div class="col-sm-6 header-brand-left">\n      <a class="brand" href="https://www.usagold.com">\n       <img alt="USA Gold" height="52" src="https://www.usagold.com/images/logoGGG-2017.png" title="USA Gold" width="340"/>\n      </a>\n      <div>\n       Coins &amp; bullion since 1973\n      </div>\n     </div>\n     <div class="col-sm-6 header-brand-right">\n      <div>\n       <img alt="" height="72" src="https://www.usagold.com/images/newheaderlogo2017.png" width="325"/>\n      </div>\n      1-800-869-5115 |\n      <a href="#" onclick="openForm()">\n       <span class="fas fa-search">\n       </span>\n      </a>\n      |\n      <a href="mailto:orderdesk@usagold.com">\n       <span class="fa fa-envelope">\n       </span>\n       <span class="screen-reader-only">\n        Email Us\n       </span>\n      </a>\n      <div class="search-popup" id="navSearch">\n       <form action="//www.google.com/search" id="SearchForm" method="get" target="_blank">\n        <center>\n         <p>\n          <input name="sitesearch" type="hidden" value="usagold.com"/>\n          <label class="screen-reader-only" for="search">\n           Search\n          </label>\n          <input id="search" maxlength="217" name="q" placeholder="Search USAGOLD.com" size="40" type="text"/>\n         </p>\n        </center>\n       </form>\n      </div>\n     </div>\n    </div>\n    <!-- END .header-brand -->\n    <!-- BEGIN DESKTOP MENU -->\n    <nav class="navbar navbar-expand-lg header-nav">\n     <a aria-controls="MainNav" aria-expanded="true" class="navbar-toggle" data-target="#MainNav" data-toggle="collapse" href="#">\n      <span class="fa fa-bars">\n      </span>\n      <span class="screen-reader-only">\n       mobile\n\t\t\t\t\tmenu\n      </span>\n     </a>\n     <div class="navbar-collapse collapse in justify-content-md-center" id="MainNav">\n      <ul class="nav navbar-nav" id="left-menu">\n       <li class="nav-item">\n        <a class="nav-link" href="https://www.usagold.com">\n         Home\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         About Us\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/aboutus.html">\n           About Us\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.bbb.org/denver/business-reviews/gold-silver-and-platinum-dealers/usagold-in-denver-co-4218#sealclick">\n           Better\n\t\t\t\t\tBusiness Bureau rating\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.bbb.org/us/co/denver/profile/precious-metal-dealers/usagold-0885-4218/customer-reviews">\n           Better\n\t\t\t\t\tBusiness Bureau reviews\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpm/about-testimonials.html">\n           Client\n\t\t\t\t\ttestimonials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldcompanyduediligence.html" tabindex="-1">\n           Why USAGOLD? 7 Reasons\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Gold News\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/dailyquotes.html">\n           Daily market report\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpmforum/">\n           Today\'s gold news &amp; opinion\n\t\t\t\t\t[blog]\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/gold-price-live.html" tabindex="-1">\n           News Wire\n\t\t\t\t\t(London) + Live Prices, Chart\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/newsviewsarchive/">\n           News &amp; Views monthly newsletter (archive)\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Getting Started\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/productspage.html" tabindex="-1">\n           How to buy\n\t\t\t\t\tgold\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldsilverbuyers.html" tabindex="-1">\n           How to\n\t\t\t\t\tsell gold\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpm/goldhelp.html" tabindex="-1">\n           Gold\n\t\t\t\t\tinvestment Q&amp;A\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/howtochooseagoldfirm.html" tabindex="-1">\n           How\n\t\t\t\t\tto choose a gold firm\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/safestorageqa.html" tabindex="-1">\n           Storage\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/cpmforum/financial-planners-precious-metals-access/">\n           Financial planners &amp; advisors\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Prices\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/gold-price-live.html" tabindex="-1">\n           Live gold\n\t\t\t\t\tprice\n           <span class="txtarial9white">\n            +charts-news-opinion\n           </span>\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/live-silver-price-today.html" tabindex="-1">\n           Live silver price\n           <span class="txtarial9white">\n            +charts-news-opinion\n           </span>\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/gold/price.html" tabindex="-1">\n           Gold coin\n\t\t\t\t\tprices\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/silver/silverprice.html" tabindex="-1">\n           Silver\n\t\t\t\t\tcoin prices\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="//www.usagold.com/reference/prices/goldhistory.php" tabindex="-1">\n           Daily\n\t\t\t\t\tGold price history\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="//www.usagold.com/reference/prices/silverhistory.php" tabindex="-1">\n           Daily\n\t\t\t\t\tSilver price history\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/cpmforum/goldtradinghours/">\n           Gold trading hours (global)\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/cpmforum/category/price-predictions-from-prominent-players/">\n           Gold price predictions (updated regularly)\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         IRA Rollovers\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldIRA.html" tabindex="-1">\n           Launching your\n\t\t\t\t\tIRA\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldIRArollover.html" tabindex="-1">\n           How to do\n\t\t\t\t\ta rollover\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldIRAeligiblelist.html" tabindex="-1">\n           Eligible gold and silver items\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/checkbookIRAsalert.html" tabindex="-1">\n           Checkbook IRAs\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Online Order Desk\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com" tabindex="-1">\n           Online Order Desk\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/bullion-gold-coins-bars/" tabindex="-1">\n           Modern gold bullion coins and bars\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/modern-bullion/" tabindex="-1">\n           Modern silver bullion coins and bars\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/historic-coins/" tabindex="-1">\n           Historic fractional gold coins\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/historic-us-coins/" tabindex="-1">\n           Historic U.S. gold coins\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/collectible-coins/" tabindex="-1">\n           Collectible coins\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://onlineorderdesk.usagold.com/sb/current-special/">\n           Current special\n\t\t\t\t\toffers\n          </a>\n          <br/>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Reference\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpmforum/referencelibraryindex/" tabindex="-1">\n           Index :\n           <span class="txtarial9">\n            Charts + Tables + Articles\n           </span>\n          </a>\n         </li>\n        </ul>\n       </li>\n      </ul>\n      <!-- END : Desktop Menu -->\n     </div>\n    </nav>\n    <!-- END DESKTOP MENU -->\n    <div class="header-spot-date">\n     <div class="row">\n      <div class="col-12">\n       <span class="header-spot-date-label">\n        Current Spot\n\t\t\t\t\t\tPrices:\n       </span>\n       11:26 am Sat. November 7, 2020 (USMT)\n      </div>\n     </div>\n    </div>\n    <!-- END .header-date -->\n    <div class="header-spot-price">\n     <div class="row">\n      <div class="col-sm-6">\n       Gold $1,954.07\n       <img alt="Up Arrow" height="12" src="https://www.usagold.com/images/arrow-up.gif" width="13">\n        <span class="green">\n         $1.94\n        </span>\n       </img>\n      </div>\n      <div class="col-sm-6">\n       Silver $25.69\n       <img alt="Up Arrow" height="12" src="https://www.usagold.com/images/arrow-up.gif" width="13">\n        <span class="green">\n         $0.23\n        </span>\n       </img>\n      </div>\n     </div>\n    </div>\n    <!-- END .header-price -->\n   </div>\n   <!-- END DESKTOP HEADER-->\n   <div align="center" class="mobileonly" id="header-mobile" style="margin-top:10px;">\n    <!-- START MOBILE HEADER -->\n    <div align="center" class="mobile-brand padding10">\n     <img alt="USA Gold" height="37" src="//www.usagold.com/mobile/logomobile240.png" width="240"/>\n     <br/>\n     <em class="txtpalatino11">\n      Coins &amp; Bullion since 1973\n     </em>\n    </div>\n    <!-- BEGIN MOBILE MENU -->\n    <nav class="navbar navbar-expand-lg mobile-nav" id="mobile-nav" style="background-color:#660033;">\n     <div class="center" id="mobile-button-menu">\n      <button aria-controls="MobileNav" aria-expanded="false" aria-label="Toggle navigation" class="button btn-icon btn-red" data-target="#MobileNav" data-toggle="collapse" type="button">\n       <span class="fa fa-bars">\n       </span>\n       <span class="screen-reader-only">\n        Menu\n       </span>\n      </button>\n      <a class="button btn-icon btn-red" href="mailto:orderdesk@usagold.com">\n       <span class="fa fa-envelope">\n       </span>\n       <span class="screen-reader-only">\n        email us\n       </span>\n      </a>\n      <a class="button btn-icon btn-red" href="tel:1-800-869-5115">\n       <span class="fa fa-phone">\n       </span>\n       <span class="screen-reader-only">\n        call us\n       </span>\n      </a>\n     </div>\n     <div class="navbar-collapse collapse in justify-content-md-center" id="MobileNav">\n      <ul class="nav navbar-nav">\n       <li class="nav-item">\n        <a class="nav-link" href="https://www.usagold.com/">\n         Home\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         About Us\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/aboutus.html">\n           About Us\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.bbb.org/denver/business-reviews/gold-silver-and-platinum-dealers/usagold-in-denver-co-4218#sealclick">\n           Better\n\t\t\t\t\t\t\tBusiness Bureau rating\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.bbb.org/us/co/denver/profile/precious-metal-dealers/usagold-0885-4218/customer-reviews">\n           Better\n\t\t\t\t\t\t\tBusiness Bureau reviews\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpm/about-testimonials.html">\n           Client\n\t\t\t\t\t\t\ttestimonials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldcompanyduediligence.html" tabindex="-1">\n           Why USA Gold? 7 Reasons\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Gold News\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/dailyquotes.html">\n           Daily market\n\t\t\t\t\t\t\treport\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpmforum/">\n           Today\'s gold news &amp;\n\t\t\t\t\t\t\topinion [blog]\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/gold-price-live.html" tabindex="-1">\n           Gold News Wire\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/newsviewsarchive/">\n           News &amp; Views monthly newsletter (archive)\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Getting Started\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/productspage.html" tabindex="-1">\n           How\n\t\t\t\t\t\t\tto buy gold\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/goldsilverbuyers.html" tabindex="-1">\n           How to sell gold\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/cpm/goldhelp.html" tabindex="-1">\n           Gold\n\t\t\t\t\t\t\tinvestment Q&amp;A\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/howtochooseagoldfirm.html" tabindex="-1">\n           How to choose a gold firm\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/safestorageqa.html" tabindex="-1">\n           Storage\n          </a>\n         </li>\n         <li>\n          <a href="https://www.usagold.com/cpmforum/financial-planners-precious-metals-access/">\n           Financial planners &amp; advisors\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item dropdown">\n        <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">\n         Prices\n         <span class="caret">\n         </span>\n        </a>\n        <ul class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="https://www.usagold.com/gold-price-live.html" tabindex="-1">\n           Live gold price\n           <span class="txtarial9white">\n            +charts-news-opinion\n           </span>\n          </a>\n         </li>\n         <li>\n          

In [16]:
for tag in soup.find_all("td" , class_="text"):
    print(tag)

<td align="left" class="text" width="90">06 Nov 2020</td>
<td align="left" class="text" width="60">1951.46</td>
<td align="left" class="text" width="90">05 Nov 2020</td>
<td align="left" class="text" width="60">1945.66</td>
<td align="left" class="text" width="90">04 Nov 2020</td>
<td align="left" class="text" width="60">1904.93</td>
<td align="left" class="text" width="90">03 Nov 2020</td>
<td align="left" class="text" width="60">1914.31</td>
<td align="left" class="text" width="90">02 Nov 2020</td>
<td align="left" class="text" width="60">1894.86</td>
<td align="left" class="text" width="90">30 Oct 2020</td>
<td align="left" class="text" width="60">1878.90</td>
<td align="left" class="text" width="90">29 Oct 2020</td>
<td align="left" class="text" width="60">1868.63</td>
<td align="left" class="text" width="90">28 Oct 2020</td>
<td align="left" class="text" width="60">1879.62</td>
<td align="left" class="text" width="90">27 Oct 2020</td>
<td align="left" class="text" width="60">1905.30</td>
<td align="left" class="text" width="90">26 Oct 2020</td>
<td align="left" class="text" width="60">1902.33</td>
<td align="left" class="text" width="90">23 Oct 2020</td>
<td align="left" class="text" width="60">1901.73</td>
<td align="left" class="text" width="90">22 Oct 2020</td>
<td align="left" class="text" width="60">1905.10</td>
<td align="left" class="text" width="90">21 Oct 2020</td>
<td align="left" class="text" width="60">1921.49</td>
<td align="left" class="text" width="90">20 Oct 2020</td>
<td align="left" class="text" width="60">1910.89</td>
<td align="left" class="text" width="90">19 Oct 2020</td>
<td align="left" class="text" width="60">1903.14</td>
<td align="left" class="text" width="90">16 Oct 2020</td>
<td align="left" class="text" width="60">1899.04</td>
<td align="left" class="text" width="90">15 Oct 2020</td>
<td align="left" class="text" width="60">1906.46</td>
<td align="left" class="text" width="90">14 Oct 2020</td>
<td align="left" class="text" width="60">1898.35</td>
<td align="left" class="text" width="90">13 Oct 2020</td>
<td align="left" class="text" width="60">1893.56</td>
<td align="left" class="text" width="90">12 Oct 2020</td>
<td align="left" class="text" width="60">1924.90</td>
<td align="left" class="text" width="90">09 Oct 2020</td>
<td align="left" class="text" width="60">1930.33</td>
<td align="left" class="text" width="90">08 Oct 2020</td>
<td align="left" class="text" width="60">1895.30</td>
<td align="left" class="text" width="90">07 Oct 2020</td>
<td align="left" class="text" width="60">1887.07</td>
<td align="left" class="text" width="90">06 Oct 2020</td>
<td align="left" class="text" width="60">1880.15</td>
<td align="left" class="text" width="90">05 Oct 2020</td>
<td align="left" class="text" width="60">1912.40</td>
<td align="left" class="text" width="90">02 Oct 2020</td>
<td align="left" class="text" width="60">1899.66</td>
<td align="left" class="text" width="90">01 Oct 2020</td>
<td align="left" class="text" width="60">1903.73</td>
<td align="left" class="text" width="90">30 Sep 2020</td>
<td align="left" class="text" width="60">1887.78</td>
<td align="left" class="text" width="90">29 Sep 2020</td>
<td align="left" class="text" width="60">1896.80</td>
<td align="left" class="text" width="90">28 Sep 2020</td>
<td align="left" class="text" width="60">1882.46</td>
<td align="left" class="text" width="90">25 Sep 2020</td>
<td align="left" class="text" width="60">1861.33</td>
<td align="left" class="text" width="90">24 Sep 2020</td>
<td align="left" class="text" width="60">1867.99</td>
<td align="left" class="text" width="90">23 Sep 2020</td>
<td align="left" class="text" width="60">1855.03</td>
<td align="left" class="text" width="90">22 Sep 2020</td>
<td align="left" class="text" width="60">1904.40</td>
<td align="left" class="text" width="90">21 Sep 2020</td>
<td align="left" class="text" width="60">1917.23</td>
<td align="left" class="text" width="90">18 Sep 2020</td>
<td align="left" class="text" width="60">1950.39</td>
<td align="left" class="text" width="90">17 Sep 2020</td>
<td align="left" class="text" width="60">1947.17</td>
<td align="left" class="text" width="90">16 Sep 2020</td>
<td align="left" class="text" width="60">1959.86</td>
<td align="left" class="text" width="90">15 Sep 2020</td>
<td align="left" class="text" width="60">1953.92</td>
<td align="left" class="text" width="90">14 Sep 2020</td>
<td align="left" class="text" width="60">1957.40</td>
<td align="left" class="text" width="90">11 Sep 2020</td>
<td align="left" class="text" width="60">1940.43</td>
<td align="left" class="text" width="90">10 Sep 2020</td>
<td align="left" class="text" width="60">1943.98</td>
<td align="left" class="text" width="90">09 Sep 2020</td>
<td align="left" class="text" width="60">1947.44</td>
<td align="left" class="text" width="90">08 Sep 2020</td>
<td align="left" class="text" width="60">1930.53</td>
<td align="left" class="text" width="90">07 Sep 2020</td>
<td align="left" class="text" width="60">1930.84</td>
<td align="left" class="text" width="90">04 Sep 2020</td>
<td align="left" class="text" width="60">1933.52</td>
<td align="left" class="text" width="90">03 Sep 2020</td>
<td align="left" class="text" width="60">1927.43</td>
<td align="left" class="text" width="90">02 Sep 2020</td>
<td align="left" class="text" width="60">1944.84</td>
<td align="left" class="text" width="90">01 Sep 2020</td>
<td align="left" class="text" width="60">1972.58</td>
<td align="left" class="text" width="90">31 Aug 2020</td>
<td align="left" class="text" width="60">1967.80</td>
<td align="left" class="text" width="90">28 Aug 2020</td>
<td align="left" class="text" width="60">1964.77</td>
<td align="left" class="text" width="90">27 Aug 2020</td>
<td align="left" class="text" width="60">1928.18</td>
<td align="left" class="text" width="90">26 Aug 2020</td>
<td align="left" class="text" width="60">1953.67</td>
<td align="left" class="text" width="90">25 Aug 2020</td>
<td align="left" class="text" width="60">1929.80</td>
<td align="left" class="text" width="90">24 Aug 2020</td>
<td align="left" class="text" width="60">1930.15</td>
<td align="left" class="text" width="90">21 Aug 2020</td>
<td align="left" class="text" width="60">1940.90</td>
<td align="left" class="text" width="90">20 Aug 2020</td>
<td align="left" class="text" width="60">1952.50</td>
<td align="left" class="text" width="90">19 Aug 2020</td>
<td align="left" class="text" width="60">1927.55</td>
<td align="left" class="text" width="90">18 Aug 2020</td>
<td align="left" class="text" width="60">2005.40</td>
<td align="left" class="text" width="90">17 Aug 2020</td>
<td align="left" class="text" width="60">1983.73</td>
<td align="left" class="text" width="90">14 Aug 2020</td>
<td align="left" class="text" width="60">1944.27</td>
<td align="left" class="text" width="90">13 Aug 2020</td>
<td align="left" class="text" width="60">1957.49</td>
<td align="left" class="text" width="90">12 Aug 2020</td>
<td align="left" class="text" width="60">1922.09</td>
<td align="left" class="text" width="90">11 Aug 2020</td>
<td align="left" class="text" width="60">1909.30</td>
<td align="left" class="text" width="90">10 Aug 2020</td>
<td align="left" class="text" width="60">2028.38</td>
<td align="left" class="text" width="90">07 Aug 2020</td>
<td align="left" class="text" width="60">2035.21</td>
<td align="left" class="text" width="90">06 Aug 2020</td>
<td align="left" class="text" width="60">2069.29</td>
<td align="left" class="text" width="90">05 Aug 2020</td>
<td align="left" class="text" width="60">2036.82</td>
<td align="left" class="text" width="90">04 Aug 2020</td>
<td align="left" class="text" width="60">2031.00</td>
<td align="left" class="text" width="90">03 Aug 2020</td>
<td align="left" class="text" width="60">1975.60</td>
<td align="left" class="text" width="90">31 Jul 2020</td>
<td align="left" class="text" width="60">1975.69</td>
<td align="left" class="text" width="90">30 Jul 2020</td>
<td align="left" class="text" width="60">1957.07</td>
<td align="left" class="text" width="90">29 Jul 2020</td>
<td align="left" class="text" width="60">1966.50</td>
<td align="left" class="text" width="90">28 Jul 2020</td>
<td align="left" class="text" width="60">1956.07</td>
<td align="left" class="text" width="90">27 Jul 2020</td>
<td align="left" class="text" width="60">1965.50</td>
<td align="left" class="text" width="90">24 Jul 2020</td>
<td align="left" class="text" width="60">1901.60</td>
<td align="left" class="text" width="90">23 Jul 2020</td>
<td align="left" class="text" width="60">1885.69</td>
<td align="left" class="text" width="90">22 Jul 2020</td>
<td align="left" class="text" width="60">1870.20</td>
<td align="left" class="text" width="90">21 Jul 2020</td>
<td align="left" class="text" width="60">1843.03</td>
<td align="left" class="text" width="90">20 Jul 2020</td>
<td align="left" class="text" width="60">1818.26</td>
<td align="left" class="text" width="90">17 Jul 2020</td>
<td align="left" class="text" width="60">1810.01</td>
<td align="left" class="text" width="90">16 Jul 2020</td>
<td align="left" class="text" width="60">1798.45</td>
<td align="left" class="text" width="90">15 Jul 2020</td>
<td align="left" class="text" width="60">1813.16</td>
<td align="left" class="text" width="90">14 Jul 2020</td>
<td align="left" class="text" width="60">1809.60</td>
<td align="left" class="text" width="90">13 Jul 2020</td>
<td align="left" class="text" width="60">1802.60</td>
<td align="left" class="text" width="90">10 Jul 2020</td>
<td align="left" class="text" width="60">1799.21</td>
<td align="left" class="text" width="90">09 Jul 2020</td>
<td align="left" class="text" width="60">1804.10</td>
<td align="left" class="text" width="90">08 Jul 2020</td>
<td align="left" class="text" width="60">1809.16</td>
<td align="left" class="text" width="90">07 Jul 2020</td>
<td align="left" class="text" width="60">1794.54</td>
<td align="left" class="text" width="90">06 Jul 2020</td>
<td align="left" class="text" width="60">1785.90</td>
<td align="left" class="text" width="90">03 Jul 2020</td>
<td align="left" class="text" width="60">1775.30</td>
<td align="left" class="text" width="90">02 Jul 2020</td>
<td align="left" class="text" width="60">1775.78</td>
<td align="left" class="text" width="90">01 Jul 2020</td>
<td align="left" class="text" width="60">1768.44</td>
<td align="left" class="text" width="90">30 Jun 2020</td>
<td align="left" class="text" width="60">1783.40</td>
<td align="left" class="text" width="90">29 Jun 2020</td>
<td align="left" class="text" width="60">1773.09</td>
<td align="left" class="text" width="90">26 Jun 2020</td>
<td align="left" class="text" width="60">1771.23</td>
<td align="left" class="text" width="90">25 Jun 2020</td>
<td align="left" class="text" width="60">1765.88</td>
<td align="left" class="text" width="90">24 Jun 2020</td>
<td align="left" class="text" width="60">1762.22</td>
<td align="left" class="text" width="90">23 Jun 2020</td>
<td align="left" class="text" width="60">1769.07</td>
<td align="left" class="text" width="90">22 Jun 2020</td>
<td align="left" class="text" width="60">1755.52</td>
<td align="left" class="text" width="90">19 Jun 2020</td>
<td align="left" class="text" width="60">1743.48</td>
<td align="left" class="text" width="90">18 Jun 2020</td>
<td align="left" class="text" width="60">1723.57</td>
<td align="left" class="text" width="90">17 Jun 2020</td>
<td align="left" class="text" width="60">1727.82</td>
<td align="left" class="text" width="90">16 Jun 2020</td>
<td align="left" class="text" width="60">1726.65</td>
<td align="left" class="text" width="90">15 Jun 2020</td>
<td align="left" class="text" width="60">1723.90</td>
<td align="left" class="text" width="90">12 Jun 2020</td>
<td align="left" class="text" width="60">1730.26</td>
<td align="left" class="text" width="90">11 Jun 2020</td>
<td align="left" class="text" width="60">1726.77</td>
<td align="left" class="text" width="90">10 Jun 2020</td>
<td align="left" class="text" width="60">1735.64</td>
<td align="left" class="text" width="90">09 Jun 2020</td>
<td align="left" class="text" width="60">1712.60</td>
<td align="left" class="text" width="90">08 Jun 2020</td>
<td align="left" class="text" width="60">1697.50</td>
<td align="left" class="text" width="90">05 Jun 2020</td>
<td align="left" class="text" width="60">1683.86</td>
<td align="left" class="text" width="90">04 Jun 2020</td>
<td align="left" class="text" width="60">1712.20</td>
<td align="left" class="text" width="90">03 Jun 2020</td>
<td align="left" class="text" width="60">1700.71</td>
<td align="left" class="text" width="90">02 Jun 2020</td>
<td align="left" class="text" width="60">1726.96</td>
<td align="left" class="text" width="90">01 Jun 2020</td>
<td align="left" class="text" width="60">1741.90</td>
<td align="left" class="text" width="90">29 May 2020</td>
<td align="left" class="text" width="60">1729.92</td>
<td align="left" class="text" width="90">28 May 2020</td>
<td align="left" class="text" width="60">1722.06</td>
<td align="left" class="text" width="90">27 May 2020</td>
<td align="left" class="text" width="60">1711.01</td>
<td align="left" class="text" width="90">26 May 2020</td>
<td align="left" class="text" width="60">1712.87</td>
<td align="left" class="text" width="90">25 May 2020</td>
<td align="left" class="text" width="60">1727.02</td>
<td align="left" class="text" width="90">22 May 2020</td>
<td align="left" class="text" width="60">1736.22</td>
<td align="left" class="text" width="90">21 May 2020</td>
<td align="left" class="text" width="60">1726.34</td>
<td align="left" class="text" width="90">20 May 2020</td>
<td align="left" class="text" width="60">1747.40</td>
<td align="left" class="text" width="90">19 May 2020</td>
<td align="left" class="text" width="60">1746.20</td>
<td align="left" class="text" width="90">18 May 2020</td>
<td align="left" class="text" width="60">1735.05</td>
<td align="left" class="text" width="90">15 May 2020</td>
<td align="left" class="text" width="60">1742.33</td>
<td align="left" class="text" width="90">14 May 2020</td>
<td align="left" class="text" width="60">1732.87</td>
<td align="left" class="text" width="90">13 May 2020</td>
<td align="left" class="text" width="60">1718.81</td>
<td align="left" class="text" width="90">12 May 2020</td>
<td align="left" class="text" width="60">1702.65</td>
<td align="left" class="text" width="90">11 May 2020</td>
<td align="left" class="text" width="60">1698.01</td>
<td align="left" class="text" width="90">08 May 2020</td>
<td align="left" class="text" width="60">1702.22</td>
<td align="left" class="text" width="90">07 May 2020</td>
<td align="left" class="text" width="60">1714.50</td>
<td align="left" class="text" width="90">06 May 2020</td>
<td align="left" class="text" width="60">1690.12</td>
<td align="left" class="text" width="90">05 May 2020</td>
<td align="left" class="text" width="60">1704.05</td>
<td align="left" class="text" width="90">04 May 2020</td>
<td align="left" class="text" width="60">1703.90</td>
<td align="left" class="text" width="90">01 May 2020</td>
<td align="left" class="text" width="60">1700.40</td>
<td align="left" class="text" width="90">30 Apr 2020</td>
<td align="left" class="text" width="60">1688.23</td>
<td align="left" class="text" width="90">29 Apr 2020</td>
<td align="left" class="text" width="60">1714.20</td>
<td align="left" class="text" width="90">28 Apr 2020</td>
<td align="left" class="text" width="60">1704.50</td>
<td align="left" class="text" width="90">27 Apr 2020</td>
<td align="left" class="text" width="60">1709.65</td>
<td align="left" class="text" width="90">24 Apr 2020</td>
<td align="left" class="text" width="60">1729.05</td>
<td align="left" class="text" width="90">23 Apr 2020</td>
<td align="left" class="text" width="60">1728.67</td>
<td align="left" class="text" width="90">22 Apr 2020</td>
<td align="left" class="text" width="60">1711.74</td>
<td align="left" class="text" width="90">21 Apr 2020</td>
<td align="left" class="text" width="60">1687.85</td>
<td align="left" class="text" width="90">20 Apr 2020</td>
<td align="left" class="text" width="60">1691.11</td>
<td align="left" class="text" width="90">17 Apr 2020</td>
<td align="left" class="text" width="60">1684.75</td>
<td align="left" class="text" width="90">16 Apr 2020</td>
<td align="left" class="text" width="60">1715.50</td>
<td align="left" class="text" width="90">15 Apr 2020</td>
<td align="left" class="text" width="60">1716.00</td>
<td align="left" class="text" width="90">14 Apr 2020</td>
<td align="left" class="text" width="60">1726.40</td>
<td align="left" class="text" width="90">13 Apr 2020</td>
<td align="left" class="text" width="60">1717.72</td>
<td align="left" class="text" width="90">10 Apr 2020</td>
<td align="left" class="text" width="60">1688.78</td>
<td align="left" class="text" width="90">09 Apr 2020</td>
<td align="left" class="text" width="60">1683.80</td>
<td align="left" class="text" width="90">08 Apr 2020</td>
<td align="left" class="text" width="60">1647.59</td>
<td align="left" class="text" width="90">07 Apr 2020</td>
<td align="left" class="text" width="60">1648.53</td>
<td align="left" class="text" width="90">06 Apr 2020</td>
<td align="left" class="text" width="60">1663.51</td>
<td align="left" class="text" width="90">03 Apr 2020</td>
<td align="left" class="text" width="60">1618.13</td>
<td align="left" class="text" width="90">02 Apr 2020</td>
<td align="left" class="text" width="60">1613.16</td>
<td align="left" class="text" width="90">01 Apr 2020</td>
<td align="left" class="text" width="60">1592.12</td>
<td align="left" class="text" width="90">31 Mar 2020</td>
<td align="left" class="text" width="60">1578.93</td>
<td align="left" class="text" width="90">30 Mar 2020</td>
<td align="left" class="text" width="60">1616.70</td>
<td align="left" class="text" width="90">27 Mar 2020</td>
<td align="left" class="text" width="60">1627.56</td>
<td align="left" class="text" width="90">26 Mar 2020</td>
<td align="left" class="text" width="60">1626.32</td>
<td align="left" class="text" width="90">25 Mar 2020</td>
<td align="left" class="text" width="60">1611.15</td>
<td align="left" class="text" width="90">24 Mar 2020</td>
<td align="left" class="text" width="60">1634.40</td>
<td align="left" class="text" width="90">23 Mar 2020</td>
<td align="left" class="text" width="60">1567.03</td>
<td align="left" class="text" width="90">20 Mar 2020</td>
<td align="left" class="text" width="60">1498.39</td>
<td align="left" class="text" width="90">19 Mar 2020</td>
<td align="left" class="text" width="60">1471.47</td>
<td align="left" class="text" width="90">18 Mar 2020</td>
<td align="left" class="text" width="60">1498.75</td>
<td align="left" class="text" width="90">17 Mar 2020</td>
<td align="left" class="text" width="60">1537.79</td>
<td align="left" class="text" width="90">16 Mar 2020</td>
<td align="left" class="text" width="60">1507.20</td>
<td align="left" class="text" width="90">13 Mar 2020</td>
<td align="left" class="text" width="60">1529.29</td>
<td align="left" class="text" width="90">12 Mar 2020</td>
<td align="left" class="text" width="60">1576.95</td>
<td align="left" class="text" width="90">11 Mar 2020</td>
<td align="left" class="text" width="60">1643.42</td>
<td align="left" class="text" width="90">10 Mar 2020</td>
<td align="left" class="text" width="60">1652.50</td>
<td align="left" class="text" width="90">09 Mar 2020</td>
<td align="left" class="text" width="60">1666.61</td>
<td align="left" class="text" width="90">06 Mar 2020</td>
<td align="left" class="text" width="60">1674.52</td>
<td align="left" class="text" width="90">05 Mar 2020</td>
<td align="left" class="text" width="60">1674.67</td>
<td align="left" class="text" width="90">04 Mar 2020</td>
<td align="left" class="text" width="60">1636.48</td>
<td align="left" class="text" width="90">03 Mar 2020</td>

In [9]:
tag.getText()

'02 Nov 2020'

In [11]:
tag['align']

'left'

In [45]:
links = []
ul = soup.find( "ul", {"id": "goldpriceyearlinks"} )
for li in ul.find_all("li"):
    a = li.find("a")
    print(a.getText(),":",a["href"])
    links.append(a["href"])

2020 : https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2020
2019 : https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2019
2018 : https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2018
2017 : https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2017
2016 : https://www.usagold.com/reference/goldprices/2016.html
2015 : https://www.usagold.com/reference/goldprices/2015.html
2014 : https://www.usagold.com/reference/goldprices/2014.html
2013 : https://www.usagold.com/reference/goldprices/2013.html
2012 : https://www.usagold.com/reference/goldprices/2012.html
2011 : https://www.usagold.com/reference/goldprices/2011.html
2010 : https://www.usagold.com/reference/goldprices/2010.html
2009 : https://www.usagold.com/reference/goldprices/2009.html
2008 : https://www.usagold.com/reference/goldprices/2008.html
2007 : https://www.usagold.com/reference/goldprices/2007.html
2006 : https://www.usagold.com/reference/goldprices/2006.html
2005 : https://www.usagold.com/reference/goldprices/2005.html
2004 : https://www.usagold.com/reference/goldprices/2004.html
2003 : https://www.usagold.com/reference/goldprices/2003.html
2002 : https://www.usagold.com/reference/goldprices/2002.html
2001 : https://www.usagold.com/reference/goldprices/2001.html
2000 : https://www.usagold.com/reference/goldprices/2000.html
1999 : https://www.usagold.com/reference/goldprices/1999.html
1998 : https://www.usagold.com/reference/goldprices/1998.html
1997 : https://www.usagold.com/reference/goldprices/1997.html
1996 : https://www.usagold.com/reference/goldprices/1996.html
1995 : https://www.usagold.com/reference/goldprices/1995.html
1994 : https://www.usagold.com/reference/goldprices/1994.html
1993 : https://www.usagold.com/reference/goldprices/1993.html
1992 : https://www.usagold.com/reference/goldprices/1992.html
1991 : https://www.usagold.com/reference/goldprices/1991.html
1990 : https://www.usagold.com/reference/goldprices/1990.html
1989 : https://www.usagold.com/reference/goldprices/1989.html
1988 : https://www.usagold.com/reference/goldprices/1988.html
1987 : https://www.usagold.com/reference/goldprices/1987.html
1986 : https://www.usagold.com/reference/goldprices/1986.html
1985 : https://www.usagold.com/reference/goldprices/1985.html
1984 : https://www.usagold.com/reference/goldprices/1984.html
1983 : https://www.usagold.com/reference/goldprices/1983.html
1982 : https://www.usagold.com/reference/goldprices/1982.html
1981 : https://www.usagold.com/reference/goldprices/1981.html
1980 : https://www.usagold.com/reference/goldprices/1980.html
1979 : https://www.usagold.com/reference/goldprices/1979.html
1978 : https://www.usagold.com/reference/goldprices/1978.html
1977 : https://www.usagold.com/reference/goldprices/1977.html
1976 : https://www.usagold.com/reference/goldprices/1976.html
1975 : https://www.usagold.com/reference/goldprices/1975.html
1974 : https://www.usagold.com/reference/goldprices/1974.html
1973 : https://www.usagold.com/reference/goldprices/1973.html
1972 : https://www.usagold.com/reference/goldprices/1972.html
1971 : https://www.usagold.com/reference/goldprices/1971.html
1970 : https://www.usagold.com/reference/goldprices/1970.html
1969 : https://www.usagold.com/reference/goldprices/1969.html
1968 : https://www.usagold.com/reference/goldprices/1968.html
Return to main price history : https://www.usagold.com/reference/prices/history.html

In [48]:
print(links)
links.pop()
links

['https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2020',
 'https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2019',
 'https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2018',
 'https://www.usagold.com/reference/prices/goldhistory.php?ddYears=2017',
 'https://www.usagold.com/reference/goldprices/2016.html',
 'https://www.usagold.com/reference/goldprices/2015.html',
 'https://www.usagold.com/reference/goldprices/2014.html',
 'https://www.usagold.com/reference/goldprices/2013.html',
 'https://www.usagold.com/reference/goldprices/2012.html',
 'https://www.usagold.com/reference/goldprices/2011.html',
 'https://www.usagold.com/reference/goldprices/2010.html',
 'https://www.usagold.com/reference/goldprices/2009.html',
 'https://www.usagold.com/reference/goldprices/2008.html',
 'https://www.usagold.com/reference/goldprices/2007.html',
 'https://www.usagold.com/reference/goldprices/2006.html',
 'https://www.usagold.com/reference/goldprices/2005.html',
 'https://www.usagold.com/reference/goldprices/2004.html',
 'https://www.usagold.com/reference/goldprices/2003.html',
 'https://www.usagold.com/reference/goldprices/2002.html',
 'https://www.usagold.com/reference/goldprices/2001.html',
 'https://www.usagold.com/reference/goldprices/2000.html',
 'https://www.usagold.com/reference/goldprices/1999.html',
 'https://www.usagold.com/reference/goldprices/1998.html',
 'https://www.usagold.com/reference/goldprices/1997.html',
 'https://www.usagold.com/reference/goldprices/1996.html',
 'https://www.usagold.com/reference/goldprices/1995.html',
 'https://www.usagold.com/reference/goldprices/1994.html',
 'https://www.usagold.com/reference/goldprices/1993.html',
 'https://www.usagold.com/reference/goldprices/1992.html',
 'https://www.usagold.com/reference/goldprices/1991.html',
 'https://www.usagold.com/reference/goldprices/1990.html',
 'https://www.usagold.com/reference/goldprices/1989.html',
 'https://www.usagold.com/reference/goldprices/1988.html',
 'https://www.usagold.com/reference/goldprices/1987.html',
 'https://www.usagold.com/reference/goldprices/1986.html',
 'https://www.usagold.com/reference/goldprices/1985.html',
 'https://www.usagold.com/reference/goldprices/1984.html',
 'https://www.usagold.com/reference/goldprices/1983.html',
 'https://www.usagold.com/reference/goldprices/1982.html',
 'https://www.usagold.com/reference/goldprices/1981.html',
 'https://www.usagold.com/reference/goldprices/1980.html',
 'https://www.usagold.com/reference/goldprices/1979.html',
 'https://www.usagold.com/reference/goldprices/1978.html',
 'https://www.usagold.com/reference/goldprices/1977.html',
 'https://www.usagold.com/reference/goldprices/1976.html',
 'https://www.usagold.com/reference/goldprices/1975.html',
 'https://www.usagold.com/reference/goldprices/1974.html',
 'https://www.usagold.com/reference/goldprices/1973.html',
 'https://www.usagold.com/reference/goldprices/1972.html',
 'https://www.usagold.com/reference/goldprices/1971.html',
 'https://www.usagold.com/reference/goldprices/1970.html',
 'https://www.usagold.com/reference/goldprices/1969.html',
 'https://www.usagold.com/reference/goldprices/1968.html']

In [61]:
table = soup.find("table",attrs={"id":"pricehistorytable"})
tr_li= []
for tr in table.find_all("tr"):
    tr_li.append(tr)

In [64]:
tr_li.pop(1)
tr_li.pop(0)

In [303]:
tr1_li, tr2_li = [],[]
for tr in tr_li:
    tr1 = tr.find("td",attrs={"width":"90"})
    tr2 = tr.find("td",attrs={"width":"60"})
    print(tr1.getText(),":",float( tr2.getText()) )
    tr1_li.append(tr1.getText())
    tr2_li.append(float( tr2.getText()) )

06 Nov 2020 : 1951.46
05 Nov 2020 : 1945.66
04 Nov 2020 : 1904.93
03 Nov 2020 : 1914.31
02 Nov 2020 : 1894.86
30 Oct 2020 : 1878.9
29 Oct 2020 : 1868.63
28 Oct 2020 : 1879.62
27 Oct 2020 : 1905.3
26 Oct 2020 : 1902.33
23 Oct 2020 : 1901.73
22 Oct 2020 : 1905.1
21 Oct 2020 : 1921.49
20 Oct 2020 : 1910.89
19 Oct 2020 : 1903.14
16 Oct 2020 : 1899.04
15 Oct 2020 : 1906.46
14 Oct 2020 : 1898.35
13 Oct 2020 : 1893.56
12 Oct 2020 : 1924.9
09 Oct 2020 : 1930.33
08 Oct 2020 : 1895.3
07 Oct 2020 : 1887.07
06 Oct 2020 : 1880.15
05 Oct 2020 : 1912.4
02 Oct 2020 : 1899.66
01 Oct 2020 : 1903.73
30 Sep 2020 : 1887.78
29 Sep 2020 : 1896.8
28 Sep 2020 : 1882.46
25 Sep 2020 : 1861.33
24 Sep 2020 : 1867.99
23 Sep 2020 : 1855.03
22 Sep 2020 : 1904.4
21 Sep 2020 : 1917.23
18 Sep 2020 : 1950.39
17 Sep 2020 : 1947.17
16 Sep 2020 : 1959.86
15 Sep 2020 : 1953.92
14 Sep 2020 : 1957.4
11 Sep 2020 : 1940.43
10 Sep 2020 : 1943.98
09 Sep 2020 : 1947.44
08 Sep 2020 : 1930.53
07 Sep 2020 : 1930.84
04 Sep 2020 : 1933.52
03 Sep 2020 : 1927.43
02 Sep 2020 : 1944.84
01 Sep 2020 : 1972.58
31 Aug 2020 : 1967.8
28 Aug 2020 : 1964.77
27 Aug 2020 : 1928.18
26 Aug 2020 : 1953.67
25 Aug 2020 : 1929.8
24 Aug 2020 : 1930.15
21 Aug 2020 : 1940.9
20 Aug 2020 : 1952.5
19 Aug 2020 : 1927.55
18 Aug 2020 : 2005.4
17 Aug 2020 : 1983.73
14 Aug 2020 : 1944.27
13 Aug 2020 : 1957.49
12 Aug 2020 : 1922.09
11 Aug 2020 : 1909.3
10 Aug 2020 : 2028.38
07 Aug 2020 : 2035.21
06 Aug 2020 : 2069.29
05 Aug 2020 : 2036.82
04 Aug 2020 : 2031.0
03 Aug 2020 : 1975.6
31 Jul 2020 : 1975.69
30 Jul 2020 : 1957.07
29 Jul 2020 : 1966.5
28 Jul 2020 : 1956.07
27 Jul 2020 : 1965.5
24 Jul 2020 : 1901.6
23 Jul 2020 : 1885.69
22 Jul 2020 : 1870.2
21 Jul 2020 : 1843.03
20 Jul 2020 : 1818.26
17 Jul 2020 : 1810.01
16 Jul 2020 : 1798.45
15 Jul 2020 : 1813.16
14 Jul 2020 : 1809.6
13 Jul 2020 : 1802.6
10 Jul 2020 : 1799.21
09 Jul 2020 : 1804.1
08 Jul 2020 : 1809.16
07 Jul 2020 : 1794.54
06 Jul 2020 : 1785.9
03 Jul 2020 : 1775.3
02 Jul 2020 : 1775.78
01 Jul 2020 : 1768.44
30 Jun 2020 : 1783.4
29 Jun 2020 : 1773.09
26 Jun 2020 : 1771.23
25 Jun 2020 : 1765.88
24 Jun 2020 : 1762.22
23 Jun 2020 : 1769.07
22 Jun 2020 : 1755.52
19 Jun 2020 : 1743.48
18 Jun 2020 : 1723.57
17 Jun 2020 : 1727.82
16 Jun 2020 : 1726.65
15 Jun 2020 : 1723.9
12 Jun 2020 : 1730.26
11 Jun 2020 : 1726.77
10 Jun 2020 : 1735.64
09 Jun 2020 : 1712.6
08 Jun 2020 : 1697.5
05 Jun 2020 : 1683.86
04 Jun 2020 : 1712.2
03 Jun 2020 : 1700.71
02 Jun 2020 : 1726.96
01 Jun 2020 : 1741.9
29 May 2020 : 1729.92
28 May 2020 : 1722.06
27 May 2020 : 1711.01
26 May 2020 : 1712.87
25 May 2020 : 1727.02
22 May 2020 : 1736.22
21 May 2020 : 1726.34
20 May 2020 : 1747.4
19 May 2020 : 1746.2
18 May 2020 : 1735.05
15 May 2020 : 1742.33
14 May 2020 : 1732.87
13 May 2020 : 1718.81
12 May 2020 : 1702.65
11 May 2020 : 1698.01
08 May 2020 : 1702.22
07 May 2020 : 1714.5
06 May 2020 : 1690.12
05 May 2020 : 1704.05
04 May 2020 : 1703.9
01 May 2020 : 1700.4
30 Apr 2020 : 1688.23
29 Apr 2020 : 1714.2
28 Apr 2020 : 1704.5
27 Apr 2020 : 1709.65
24 Apr 2020 : 1729.05
23 Apr 2020 : 1728.67
22 Apr 2020 : 1711.74
21 Apr 2020 : 1687.85
20 Apr 2020 : 1691.11
17 Apr 2020 : 1684.75
16 Apr 2020 : 1715.5
15 Apr 2020 : 1716.0
14 Apr 2020 : 1726.4
13 Apr 2020 : 1717.72
10 Apr 2020 : 1688.78
09 Apr 2020 : 1683.8
08 Apr 2020 : 1647.59
07 Apr 2020 : 1648.53
06 Apr 2020 : 1663.51
03 Apr 2020 : 1618.13
02 Apr 2020 : 1613.16
01 Apr 2020 : 1592.12
31 Mar 2020 : 1578.93
30 Mar 2020 : 1616.7
27 Mar 2020 : 1627.56
26 Mar 2020 : 1626.32
25 Mar 2020 : 1611.15
24 Mar 2020 : 1634.4
23 Mar 2020 : 1567.03
20 Mar 2020 : 1498.39
19 Mar 2020 : 1471.47
18 Mar 2020 : 1498.75
17 Mar 2020 : 1537.79
16 Mar 2020 : 1507.2
13 Mar 2020 : 1529.29
12 Mar 2020 : 1576.95
11 Mar 2020 : 1643.42
10 Mar 2020 : 1652.5
09 Mar 2020 : 1666.61
06 Mar 2020 : 1674.52
05 Mar 2020 : 1674.67
04 Mar 2020 : 1636.48
03 Mar 2020 : 1645.88
02 Mar 2020 : 1592.23
28 Feb 2020 : 1586.46
27 Feb 2020 : 1645.57
26 Feb 2020 : 1643.74
25 Feb 2020 : 1640.23
24 Feb 2020 : 1653.8
21 Feb 2020 : 1643.62
20 Feb 2020 : 1622.3
19 Feb 2020 : 1610.51
18 Feb 2020 : 1600.97
17 Feb 2020 : 1584.23
14 Feb 2020 : 1583.89
13 Feb 2020 : 1577.48
12 Feb 2020 : 1570.28
11 Feb 2020 : 1567.2
10 Feb 2020 : 1572.06
07 Feb 2020 : 1570.41
06 Feb 2020 : 1565.89
05 Feb 2020 : 1556.1
04 Feb 2020 : 1554.04
03 Feb 2020 : 1578.96
31 Jan 2020 : 1589.4
30 Jan 2020 : 1575.21
29 Jan 2020 : 1577.2
28 Jan 2020 : 1568.59
27 Jan 2020 : 1581.17
24 Jan 2020 : 1571.56
23 Jan 2020 : 1561.04
22 Jan 2020 : 1561.45
21 Jan 2020 : 1556.56
20 Jan 2020 : 1561.31
17 Jan 2020 : 1557.3
16 Jan 2020 : 1552.27
15 Jan 2020 : 1556.35
14 Jan 2020 : 1549.6
13 Jan 2020 : 1545.44
10 Jan 2020 : 1562.05
09 Jan 2020 : 1552.72
08 Jan 2020 : 1557.89
07 Jan 2020 : 1595.24
06 Jan 2020 : 1563.83
03 Jan 2020 : 1552.24
02 Jan 2020 : 1528.95

"chrome Extension pokemon", "Discord","Selenium"

In [304]:
type(tr2_li[0])  ,tr1_li[:5]

(float,
 ['06 Nov 2020', '05 Nov 2020', '04 Nov 2020', '03 Nov 2020', '02 Nov 2020'])

In [306]:
dictionary = {
    "Date" : tr2_li,
    "Price" : tr1_li
}

In [310]:
import pandas as pd
df = pd.DataFrame(dictionary)
df.to_csv("file.csv")

In [324]:
data = pd.read_csv("file.csv")
data.head()

   Unnamed: 0     Date        Price
0           0  1951.46  06 Nov 2020
1           1  1945.66  05 Nov 2020
2           2  1904.93  04 Nov 2020
3           3  1914.31  03 Nov 2020
4           4  1894.86  02 Nov 2020

In [312]:
import csv

In [326]:
new_data = []
for i in range(len(tr1_li)):
    
    li = []
    li.append(tr1_li[i])
    li.append(tr2_li[i])
    
    new_data.append(li)

In [327]:
new_data[0:5]

[['06 Nov 2020', 1951.46],
 ['05 Nov 2020', 1945.66],
 ['04 Nov 2020', 1904.93],
 ['03 Nov 2020', 1914.31],
 ['02 Nov 2020', 1894.86]]

In [328]:
len(new_data)

222

In [329]:
new_data.insert(0,["Date,Price"])

In [330]:
len(new_data),new_data[0:5]

(223,
 [['Date,Price'],
  ['06 Nov 2020', 1951.46],
  ['05 Nov 2020', 1945.66],
  ['04 Nov 2020', 1904.93],
  ['03 Nov 2020', 1914.31]])

In [ ]:
with open("")

In [287]:
class Cordinate(object):
    
    def __init__(self,x,y):
        self.x = x
        self.y = y
        
    def square(self):
        return self.x**2,self.y**2
    
    def distance(self,other):
        
        x_diff_sq = (self.x - other.x)**2
        y_diff_sq = (self.y - other.y)**2
        
        return (x_diff_sq+y_diff_sq) ** 0.5

In [288]:
a = Cordinate(7,8)
b = Cordinate(6,5)

In [293]:
sq = a.square()
sq[1]

64

In [155]:
a.distance(b)

3.1622776601683795

In [286]:
d = Cordinate.distance(a,b)
d

<__main__.Cordinate object at 0x000001A81A891308>

In [162]:
f = a.square()
type(f),f,f[0]

(tuple, (49, 64), 49)

In [158]:
a.x

7

# PAK Covid Repot webscrappng

In [1]:
from bs4 import BeautifulSoup as bs
import requests

In [2]:
covid_link = "https://www.worldometers.info/coronavirus/#countries"

In [4]:
req = requests.get(covid_link)

In [5]:
req = req.text

In [18]:
soop = bs(req,"html.parser")

In [26]:
table = soop.find("table",{"id":"main_table_countries_today"})
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br>Other</br></th>
<th width="20">Total<br>Cases</br></th>
<th width="30">New<br>Cases</br></th>
<th width="30">Total<br>Deaths</br></th>
<th width="30">New<br>Deaths</br></th>
<th width="30">Total<br>Recovered</br></th>
<th width="30">New<br>Recovered</br></th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>14,565,241</td>
<td>+7,029</td>
<td>390,883</td>
<td>+557</td>
<td>9,002,805</td>
<td>+4,317</td>
<td>5,171,553</td>
<td>27,016</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>15,695,695</td>
<td>+15,701</td>
<td>276,730</td>
<td>+284</td>
<td>14,090,113</td>
<td>+23,361</td>
<td>1,328,852</td>
<td>25,655</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>10,676,757</td>
<td>+68</td>
<td>316,563</td>
<td>+4</td>
<td>9,603,092</td>
<td>+151</td>
<td>757,102</td>
<td>17,187</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>15,498,737</td>
<td>+47,101</td>
<td>352,771</td>
<td>+855</td>
<td>6,044,131</td>
<td>+29,706</td>
<td>9,101,835</td>
<td>29,916</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>2,069,880</td>
<td>+28</td>
<td>49,512</td>
<td></td>
<td>1,743,672</td>
<td>+17</td>
<td>276,696</td>
<td>2,577</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>43,520</td>
<td>+22</td>
<td>1,004</td>
<td></td>
<td>32,975</td>
<td>+2</td>
<td>9,541</td>
<td>23</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>659</td>
<td></td>
<td>47</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>58,550,551</td>
<td>+69,949</td>
<td>1,387,478</td>
<td>+1,700</td>
<td>40,517,447</td>
<td>+57,554</td>
<td>16,645,626</td>
<td>102,378</td>
<td>7,511</td>
<td>178.0</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">12,450,666</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">261,790 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">7,403,847</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">4,785,029</td>
<td style="font-weight: bold; text-align:right">22,927</td>
<td style="font-weight: bold; text-align:right">37,529</td>
<td style="font-weight: bold; text-align:right">789</td>
<td style="font-weight: bold; text-align:right">179,039,707</td>
<td style="font-weight: bold; text-align:right">539,659</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,764,517</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>27</td><td>1,267</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">9,095,908</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">133,263 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">8,521,617</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,578</td>
<td style="text-align:right;font-weight:bold;">441,028</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">6,566</td>
<td style="font-weight: bold; text-align:right">96</td>
<td style="font-weight: bold; text-align:right">131,733,134</td>
<td style="font-weight: bold; text-align:right">95,093</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,385,308,309</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>152</td><td>10,395</td><td>11</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">6,052,786</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">169,016 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">5,429,158</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">454,612</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">28,397</td>
<td style="font-weight: bold; text-align:right">793</td>
<td style="font-weight: bold; text-align:right">21,900,000</td>
<td style="font-weight: bold; text-align:right">102,744</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">213,151,746</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>35</td><td>1,261</td><td>10</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">2,127,051</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">48,518 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">149,521</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,929,012</td>
<td style="font-weight: bold; text-align:right">4,582</td>
<td style="font-weight: bold; text-align:right">32,558</td>
<td style="font-weight: bold; text-align:right">743</td>
<td style="font-weight: bold; text-align:right">19,779,652</td>
<td style="font-weight: bold; text-align:right">302,763</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,330,409</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>31</td><td>1,347</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">2,089,329</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+24,581</td>
<td style="font-weight: bold; text-align:right;">36,179 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+401</td>
<td style="font-weight: bold; text-align:right">1,595,443</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+18,008</td>
<td style="text-align:right;font-weight:bold;">457,707</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">14,314</td>
<td style="font-weight: bold; text-align:right">248</td>
<td style="font-weight: bold; text-align:right">72,400,000</td>
<td style="font-weight: bold; text-align:right">496,029</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,959,155</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>70</td><td>4,034</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">1,589,219</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">42,619 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">3,054</td>
<td style="font-weight: bold; text-align:right">33,985</td>
<td style="font-weight: bold; text-align:right">911</td>
<td style="font-weight: bold; text-align:right">20,742,051</td>
<td style="font-weight: bold; text-align:right">443,567</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,761,925</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>29</td><td>1,097</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">1,493,383</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">54,626 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">1,421</td>
<td style="font-weight: bold; text-align:right">21,953</td>
<td style="font-weight: bold; text-align:right">803</td>
<td style="font-weight: bold; text-align:right">40,266,183</td>
<td style="font-weight: bold; text-align:right">591,923</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,026,070</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>46</td><td>1,245</td><td>2</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">1,380,531</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">49,261 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">539,524</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">791,746</td>
<td style="font-weight: bold; text-align:right">3,758</td>
<td style="font-weight: bold; text-align:right">22,846</td>
<td style="font-weight: bold; text-align:right">815</td>
<td style="font-weight: bold; text-align:right">20,199,829</td>
<td style="font-weight: bold; text-align:right">334,287</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,426,678</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>44</td><td>1,227</td><td>3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
<td style="font-weight: bold; text-align:right">1,366,182</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">36,902 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">1,187,053</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">142,227</td>
<td style="font-weight: bold; text-align:right">4,132</td>
<td style="font-weight: bold; text-align:right">30,120</td>
<td style="font-weight: bold; text-align:right">814</td>
<td style="font-weight: bold; text-align:right">3,661,948</td>
<td style="font-weight: bold; text-align:right">80,734</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,358,011</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>33</td><td>1,229</td><td>12</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
<td style="font-weight: bold; text-align:right">1,240,493</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">35,104 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">1,144,923</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">60,466</td>
<td style="font-weight: bold; text-align:right">2,376</td>
<td style="font-weight: bold; text-align:right">24,278</td>
<td style="font-weight: bold; text-align:right">687</td>
<td style="font-weight: bold; text-align:right">6,010,654</td>
<td style="font-weight: bold; text-align:right">117,637</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,094,723</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>41</td><td>1,456</td><td>9</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">1,032,688</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,719</td>
<td style="font-weight: bold; text-align:right;">101,373  </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+550</td>
<td style="font-weight: bold; text-align:right">774,930</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,202</td>
<td style="text-align:right;font-weight:bold;">156,385</td>
<td style="font-weight: bold; text-align:right">2,852</td>
<td style="font-weight: bold; text-align:right">7,977</td>
<td style="font-weight: bold; text-align:right">783</td>
<td style="font-weight: bold; text-align:right">2,684,780</td>
<td style="font-weight: bold; text-align:right">20,738</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">129,461,935</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>125</td><td>1,277</td><td>48</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">948,081</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">35,549 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">876,399</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">36,133</td>
<td style="font-weight: bold; text-align:right">969</td>
<td style="font-weight: bold; text-align:right">28,599</td>
<td style="font-weight: bold; text-align:right">1,072</td>
<td style="font-weight: bold; text-align:right">4,916,164</td>
<td style="font-weight: bold; text-align:right">148,298</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">33,150,631</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>35</td><td>933</td><td>7</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">918,271</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">14,239 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">593,100</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">310,932</td>
<td style="font-weight: bold; text-align:right">3,615</td>
<td style="font-weight: bold; text-align:right">10,946</td>
<td style="font-weight: bold; text-align:right">170</td>
<td style="font-weight: bold; text-align:right">26,456,866</td>
<td style="font-weight: bold; text-align:right">315,378</td>

In [47]:
for i in table.find_all("tr"):
    for j in i.find_all("a"):
        for k in j:
            if k == "Pakistan":
                m = k

In [98]:
m.parent.parent.parent

<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">28</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>
<td style="font-weight: bold; text-align:right">374,173</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,665</td>
<td style="font-weight: bold; text-align:right;">7,662 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+59</td>
<td style="font-weight: bold; text-align:right">329,828</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+897</td>
<td style="text-align:right;font-weight:bold;">36,683</td>
<td style="font-weight: bold; text-align:right">1,653</td>
<td style="font-weight: bold; text-align:right">1,681</td>
<td style="font-weight: bold; text-align:right">34</td>
<td style="font-weight: bold; text-align:right">5,180,026</td>
<td style="font-weight: bold; text-align:right">23,276</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/pakistan-population/">222,551,849</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>595</td><td>29,046</td><td>43</td>
</tr>

In [84]:
# print((m.parent.parent.parent).getText())
parent = (m.parent.parent.parent).getText()
parent_li = parent.split("\n")
parent, parent_li

('\n28\nPakistan\n374,173\n+2,665\n7,662 \n+59\n329,828\n+897\n36,683\n1,653\n1,681\n34\n5,180,026\n23,276\n222,551,849 \nAsia\n59529,04643\n',
 ['',
  '28',
  'Pakistan',
  '374,173',
  '+2,665',
  '7,662 ',
  '+59',
  '329,828',
  '+897',
  '36,683',
  '1,653',
  '1,681',
  '34',
  '5,180,026',
  '23,276',
  '222,551,849 ',
  'Asia',
  '59529,04643',
  ''])

In [85]:
parent_li.pop(0)
parent_li.pop(-1)
parent_li

['28',
 'Pakistan',
 '374,173',
 '+2,665',
 '7,662 ',
 '+59',
 '329,828',
 '+897',
 '36,683',
 '1,653',
 '1,681',
 '34',
 '5,180,026',
 '23,276',
 '222,551,849 ',
 'Asia',
 '59529,04643']

In [86]:
thead = soop.find("thead")
thead.getText()

'\n\n#\nCountry,Other\nTotalCases\nNewCases\nTotalDeaths\nNewDeaths\nTotalRecovered\nNewRecovered\nActiveCases\nSerious,Critical\nTot\xa0Cases/1M pop\nDeaths/1M pop\nTotalTests\nTests/\n1M pop\n\nPopulation\nContinent\n1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl\n\n'

In [87]:
thead_li = thead.getText().split("\n")
thead_li

['',
 '',
 '#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
 '',
 '']

In [88]:
thead_li.pop(0)
thead_li.pop(0)
thead_li.pop(-1)
thead_li.pop(-1)
thead_li

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/',
 '1M pop',
 '',
 'Population',
 'Continent',
 '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl']

In [89]:
len(thead_li),len(parent_li)

(19, 17)

In [90]:
for i in range(len(parent_li)):
    print(thead_li[i],":",parent_li[i])

# : 28
Country,Other : Pakistan
TotalCases : 374,173
NewCases : +2,665
TotalDeaths : 7,662
NewDeaths : +59
TotalRecovered : 329,828
NewRecovered : +897
ActiveCases : 36,683
Serious,Critical : 1,653
Tot Cases/1M pop : 1,681
Deaths/1M pop : 34
TotalTests : 5,180,026
Tests/ : 23,276
1M pop : 222,551,849
 : Asia
Population : 59529,04643

In [91]:
thead_li[15] = "Continent"
thead_li[1] ="Country"

In [92]:
for i in range(len(parent_li)):
    print(thead_li[i],":",parent_li[i])

# : 28
Country : Pakistan
TotalCases : 374,173
NewCases : +2,665
TotalDeaths : 7,662
NewDeaths : +59
TotalRecovered : 329,828
NewRecovered : +897
ActiveCases : 36,683
Serious,Critical : 1,653
Tot Cases/1M pop : 1,681
Deaths/1M pop : 34
TotalTests : 5,180,026
Tests/ : 23,276
1M pop : 222,551,849
Continent : Asia
Population : 59529,04643

In [109]:
from bs4 import BeautifulSoup as bs
import requests

print()

covid_link = "https://www.worldometers.info/coronavirus/#countries"

req = requests.get(covid_link)

req = req.text
soop = bs(req,"html.parser")

table = soop.find("table",{"id":"main_table_countries_today"})

name = input("Enter Country name: ")

for i in table.find_all("tr"):
    for j in i.find_all("a"):
        for k in j:
            if k == name.capitalize():
                m = k
                print()
                print(" Extracting......")
                print()

                parent = (m.parent.parent.parent).getText()
                parent_li = parent.split("\n")

                parent_li.pop(0)
                parent_li.pop(-1)

                thead = soop.find("thead")
                thead_li = thead.getText().split("\n")

                thead_li.pop(0)
                thead_li.pop(0)
                thead_li.pop(-1)
                thead_li.pop(-1)

                thead_li[15] = "Continent"
                thead_li[1] ="Country"

                for i in range(len(parent_li)):
                    print("",thead_li[i],":",parent_li[i])
else:
    print("Country Not Found")

Enter Country name: pakistan

 Extracting......

 # : 28
 Country : Pakistan
 TotalCases : 374,173
 NewCases : +2,665
 TotalDeaths : 7,662
 NewDeaths : +59
 TotalRecovered : 329,828
 NewRecovered : +897
 ActiveCases : 36,683
 Serious,Critical : 1,653
 Tot Cases/1M pop : 1,681
 Deaths/1M pop : 34
 TotalTests : 5,180,026
 Tests/ : 23,276
 1M pop : 222,551,849
 Continent : Asia
 Population : 59529,04643
Country Not Found

'Billi'